name: Run Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 16 * * 2'  # Execute every Tuesdays

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clean pip cache
        run: |
          pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r PythonProject/requirements.txt
      
      - name: Install ChromeDriver 
        run: | 
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings

      - name: List artifacts directory 
        run: |
          ls -la artifacts/

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          paths: artifacts/
